name: CI

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]
  schedule:
    # Weekly security updates check
    - cron: '0 2 * * 0'

env:
  # Ensures output is colored and unbuffered
  PYTHONUNBUFFERED: 1
  FORCE_COLOR: 1

jobs:
  # Stage 1: Code Quality Checks (fast, parallel)
  quality:
    name: Code Quality
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          version: "0.9.8"
          enable-cache: true
          cache-dependency-glob: "uv.lock"

      - name: Install Python
        run: uv python install

      - name: Install dependencies
        run: uv sync --group lint --group type

      - name: Lint with ruff
        run: uv run ruff check src/ tests/

      - name: Format check with ruff
        run: uv run ruff format --check src/ tests/

      - name: Type check with mypy
        run: uv run mypy src/

  # Stage 2: Tests (matrix across Python versions)
  test:
    name: Tests (Python ${{ matrix.python-version }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.11", "3.12", "3.13"]
    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true
          cache-dependency-glob: "uv.lock"

      - name: Install Python ${{ matrix.python-version }}
        run: uv python install ${{ matrix.python-version }}
        env:
          UV_PYTHON: ${{ matrix.python-version }}

      - name: Install dependencies
        run: uv sync --all-extras --dev

      - name: Run tests with coverage
        run: uv run pytest --cov=src --cov-report=xml --cov-report=term

      - name: Upload coverage reports
        uses: codecov/codecov-action@v3
        with:
          files: ./coverage.xml
          flags: unittests
          name: codecov-${{ matrix.python-version }}

  # Stage 3: Security Checks
  security:
    name: Security Checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true
          cache-dependency-glob: "uv.lock"

      - name: Install Python
        run: uv python install

      - name: Install dependencies
        run: uv sync --all-extras --dev

      - name: Check for known vulnerabilities
        run: uv pip audit
        continue-on-error: true  # Report but don't fail

      - name: Bandit security check
        run: uv run bandit -r src/ --exit-code 0
        continue-on-error: true

  # Stage 4: Integration Tests (optional, slower)
  integration:
    name: Integration Tests
    runs-on: ubuntu-latest
    if: github.event_name == 'push' || github.event.pull_request.draft == false
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true
          cache-dependency-glob: "uv.lock"

      - name: Install Python
        run: uv python install

      - name: Install dependencies
        run: uv sync --all-extras --dev

      - name: Run integration tests
        run: uv run pytest tests/integration/ -v
        env:
          DATABASE_URL: postgres://postgres:postgres@localhost/test_db

  # Stage 5: Build and Publish (only on success)
  build:
    name: Build Package
    runs-on: ubuntu-latest
    needs: [quality, test, security]
    if: success()
    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v6

      - name: Build distributions
        run: uv build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: python-distributions
          path: dist/

  # Stage 6: Publish to PyPI (only on version tags)
  publish:
    name: Publish to PyPI
    runs-on: ubuntu-latest
    needs: build
    if: startsWith(github.ref, 'refs/tags/v') && github.event_name == 'push'
    permissions:
      id-token: write  # Required for trusted publishing (OIDC)
    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v6

      - name: Download built distributions
        uses: actions/download-artifact@v3
        with:
          name: python-distributions
          path: dist/

      - name: Publish to PyPI
        run: uv publish
        # Uses OIDC token from GitHub, no credentials needed

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: dist/*
          body: |
            PyPI Release: https://pypi.org/project/${{ github.event.repository.name }}/
          draft: false

  # Status check: All required jobs passed
  all-checks:
    name: All Checks
    runs-on: ubuntu-latest
    needs: [quality, test, security]
    if: always()
    steps:
      - name: Decide whether the checks passed
        run: |
          if [[ "${{ needs.quality.result }}" == "failure" || "${{ needs.test.result }}" == "failure" || "${{ needs.security.result }}" == "failure" ]]; then
            echo "Some checks failed"
            exit 1
          fi
          echo "All checks passed!"
